#!/usr/bin/env ruby
# frozen_string_literal: true

# Wires the **Listen** home-screen shortcuts into the Capacitor-generated Xcode
# project (`ios/App/App.xcodeproj`).
#
# This is the app-side half of the Listen widget (`native/Widget/OTBWidget.swift`
# + `scripts/add-widget-extension.rb`). The widget and the app icon's long-press
# quick action both need to reach *into* the web app, which the shell can only do
# by loading a URL — so this script:
#
#   1. adds `native/App/OTBLaunchActions.swift` to the App target, which turns a
#      quick action or an `onthebeach://listen` deep link into a load of
#      `<server.url>/?action=listen` in the bridge's web view;
#   2. registers the `onthebeach` URL scheme (`CFBundleURLTypes`) so the widget's
#      link reaches the app at all;
#   3. registers the Home Screen quick action (`UIApplicationShortcutItems`) —
#      iOS gives apps no way to add to a *widget's* long-press menu, so the app
#      icon's is where "long press ▸ Listen" lives;
#   4. declares `NSMicrophoneUsageDescription`, without which the recogniser's
#      first `getUserMedia` call is refused by the system and Listen can never
#      work inside the native app.
#
# Like the other two injection scripts, this exists because the whole `ios/`
# directory is generated by `cap add ios` and gitignored, so none of this can
# live in git as part of the project. Run it AFTER `add-share-extension.rb` (that
# script owns the app-level Catalyst / deployment-target / CFBundleName patches).
# It is idempotent: re-running removes anything it previously added and rebuilds
# it.
#
# Usage:  ruby scripts/add-listen-shortcut.rb
#
# Requires the `xcodeproj` gem (`gem install xcodeproj`) — same as the share
# extension script (see docs/ios-native-app.md and .github/workflows/ios-build.yml).

require "xcodeproj"

# --- Paths -------------------------------------------------------------------
REPO_ROOT = File.expand_path("..", __dir__)
PROJECT_PATH = File.join(REPO_ROOT, "ios", "App", "App.xcodeproj")
NATIVE_DIR = File.join(REPO_ROOT, "native", "App")
SWIFT_SOURCE = File.join(NATIVE_DIR, "OTBLaunchActions.swift")
APP_INFO_PLIST = File.join(REPO_ROOT, "ios", "App", "App", "Info.plist")

APP_TARGET_NAME = "App"
GROUP_NAME = "OTBApp"
SWIFT_BASENAME = File.basename(SWIFT_SOURCE)

# The widget's deep link. Keep in step with `OTBLaunchActions.urlScheme` in
# native/App/OTBLaunchActions.swift and the `otbListenURL` the widget opens.
URL_SCHEME = "onthebeach"
# Keep in step with `OTBLaunchAction.shortcutType` in the same file.
LISTEN_SHORTCUT_TYPE = "otb-listen"
MIC_USAGE_DESCRIPTION =
  "On The Beach listens to what's playing so it can name the release and add it to your list."

def die(message)
  warn "add-listen-shortcut: #{message}"
  exit 1
end

die "no Xcode project at #{PROJECT_PATH} — run `bun run cap:add` first" unless File.exist?(PROJECT_PATH)
die "missing #{SWIFT_SOURCE}" unless File.exist?(SWIFT_SOURCE)

project = Xcodeproj::Project.open(PROJECT_PATH)

app_target = project.targets.find { |t| t.name == APP_TARGET_NAME }
die "no `#{APP_TARGET_NAME}` target in project — is this a Capacitor iOS project?" unless app_target

# --- Idempotency: tear down anything a previous run left behind ---------------
# Scoped strictly to our own source file and group, so a re-run never disturbs
# Capacitor's generated AppDelegate.swift or the extension targets.
app_target.source_build_phase.files
          .select { |f| f.file_ref&.path.to_s.end_with?(SWIFT_BASENAME) }
          .each { |f| f.remove_from_project }

project.main_group[GROUP_NAME]&.remove_from_project

# --- Compile the launch-action handler into the app --------------------------
# Referenced in place (native/ stays the source of truth) rather than copied
# into ios/. It's an `extension AppDelegate`, so it only compiles as part of the
# App target — never the extensions.
group = project.main_group.new_group(GROUP_NAME, NATIVE_DIR)
swift_ref = group.new_file(SWIFT_SOURCE)
app_target.add_file_references([swift_ref])

project.save

# --- Info.plist: URL scheme, quick action, microphone ------------------------
die "no app Info.plist at #{APP_INFO_PLIST} — run `bun run cap:add` first" unless File.exist?(APP_INFO_PLIST)

plist = Xcodeproj::Plist.read_from_path(APP_INFO_PLIST)
bundle_id = app_target.build_configurations.first
                      .build_settings["PRODUCT_BUNDLE_IDENTIFIER"] || "es.ricojam.onthebeach"

# 1. The URL scheme the widget opens. Merge rather than overwrite: keep any
#    other scheme the project already declares, and replace only our entry.
url_types = plist["CFBundleURLTypes"] || []
url_types = url_types.reject { |entry| Array(entry["CFBundleURLSchemes"]).include?(URL_SCHEME) }
url_types << {
  "CFBundleURLName" => bundle_id,
  "CFBundleURLSchemes" => [URL_SCHEME],
}
plist["CFBundleURLTypes"] = url_types

# 2. The app icon's long-press quick action. A static item (rather than one the
#    app registers at runtime) so it's there before the app has ever been run.
plist["UIApplicationShortcutItems"] = [
  {
    "UIApplicationShortcutItemType" => LISTEN_SHORTCUT_TYPE,
    "UIApplicationShortcutItemTitle" => "Listen",
    "UIApplicationShortcutItemSubtitle" => "Name what's playing",
    "UIApplicationShortcutItemIconSymbolName" => "waveform",
  },
]

# 3. Microphone permission. The web app records ~15s of audio for recognition;
#    WKWebView grants the page's getUserMedia (Capacitor auto-allows it), but the
#    system prompt still needs a purpose string or the app is terminated.
plist["NSMicrophoneUsageDescription"] = MIC_USAGE_DESCRIPTION

Xcodeproj::Plist.write_to_path(plist, APP_INFO_PLIST)

puts "add-listen-shortcut: wired #{SWIFT_BASENAME}, the #{URL_SCHEME}:// scheme " \
     "and the Listen quick action into #{APP_TARGET_NAME}"
