#!/usr/bin/env ruby
# frozen_string_literal: true

# Adds the native Share Extension target to the Capacitor-generated Xcode
# project (`ios/App/App.xcodeproj`).
#
# The whole `ios/` directory is generated by `cap add ios` and is gitignored, so
# the extension target can't live in git as part of the project. This script is
# the scripted equivalent of the manual Xcode steps in
# `docs/ios-native-app.md` (§2 "Add the Share Extension target"): it wires the
# hand-authored sources in `native/ShareExtension/` into a real
# `com.apple.product-type.app-extension` target so a build of the `App` scheme
# also compiles `ShareViewController.swift`. That's what lets CI compile the
# extension without anyone opening Xcode.
#
# It is idempotent: re-running it removes any ShareExtension target/group/embed
# phase it previously added and rebuilds them, so `cap add` + this script always
# yields the same project whether the extension was there before or not.
#
# Usage:  ruby scripts/add-share-extension.rb
#
# Requires the `xcodeproj` gem (`gem install xcodeproj`). CocoaPods depends on
# xcodeproj, so any machine set up to build this project already has a copy —
# but under its own Ruby; installing it into the active Ruby is the reliable
# path (see docs and .github/workflows/ios-build.yml).

require "xcodeproj"

# --- Paths -------------------------------------------------------------------
# Resolve everything relative to the repo root (this script lives in scripts/),
# so it works regardless of the caller's working directory.
REPO_ROOT = File.expand_path("..", __dir__)
PROJECT_PATH = File.join(REPO_ROOT, "ios", "App", "App.xcodeproj")
NATIVE_DIR = File.join(REPO_ROOT, "native", "ShareExtension")
SWIFT_SOURCE = File.join(NATIVE_DIR, "ShareViewController.swift")
INFO_PLIST = File.join(NATIVE_DIR, "Info.plist")
SECRETS_XCCONFIG = File.join(NATIVE_DIR, "Secrets.xcconfig")
ENTITLEMENTS = File.join(NATIVE_DIR, "ShareExtension.entitlements")

EXT_NAME = "ShareExtension"
APP_TARGET_NAME = "App"
# User-facing product name. Capacitor's generated CFBundleName is "App"; the
# macOS Sharing pane and Catalyst menu bar surface CFBundleName, so set the real
# name (see the CFBundleName patch near the end of this script).
APP_DISPLAY_NAME = "On The Beach"
# Deployment target for the whole app. This is a single-user app that runs the
# current iOS, so we target the latest (26.0) rather than carrying an older
# floor — which also comfortably clears the iOS 14 `UTType` API that
# ShareViewController.swift relies on. Applied below to the extension, the App
# target, and the project (overriding Capacitor's generated 13.0 default) so the
# whole app shares one floor instead of a 13/26 split.
DEPLOYMENT_TARGET = "26.0"

def die(message)
  warn "add-share-extension: #{message}"
  exit 1
end

die "no Xcode project at #{PROJECT_PATH} — run `bun run cap:add` first" unless File.exist?(PROJECT_PATH)
die "missing #{SWIFT_SOURCE}" unless File.exist?(SWIFT_SOURCE)
die "missing #{INFO_PLIST}" unless File.exist?(INFO_PLIST)

project = Xcodeproj::Project.open(PROJECT_PATH)

app_target = project.targets.find { |t| t.name == APP_TARGET_NAME }
die "no `#{APP_TARGET_NAME}` target in project — is this a Capacitor iOS project?" unless app_target

# --- Idempotency: tear down anything a previous run left behind ---------------
# Remove old embed phases and target dependencies that point at the extension
# first (they reference the target we're about to delete), then the target, its
# product file reference, and the source group.
app_target.build_phases.grep(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
          .select { |p| p.name == "Embed App Extensions" }
          .each { |p| p.remove_from_project }

app_target.dependencies
          .select { |d| d.target && d.target.name == EXT_NAME }
          .each { |d| d.remove_from_project }

project.targets.select { |t| t.name == EXT_NAME }.each do |t|
  t.product_reference&.remove_from_project
  t.remove_from_project
end

project.main_group[EXT_NAME]&.remove_from_project

# --- Create the extension target ---------------------------------------------
ext_target = project.new_target(
  :app_extension,
  EXT_NAME,
  :ios,
  DEPLOYMENT_TARGET,
)

# Bundle id must be a child of the app's (Apple requires the extension id to be
# prefixed by the containing app's id). Derive it from the App target so we stay
# in sync if the app id ever changes.
app_bundle_id = app_target.build_configurations.first
                          .build_settings["PRODUCT_BUNDLE_IDENTIFIER"] || "es.ricojam.onthebeach"
ext_bundle_id = "#{app_bundle_id}.#{EXT_NAME}"

# Version must match the parent app or the archive is rejected ("The
# CFBundleVersion of an app extension … must match that of its containing parent
# app"). The extension's Info.plist reads these from build settings via
# $(CURRENT_PROJECT_VERSION)/$(MARKETING_VERSION); Capacitor sets them on the App
# target but new_target leaves them empty on the extension, so mirror the App's.
app_first_settings = app_target.build_configurations.first.build_settings
ext_current_version = app_first_settings["CURRENT_PROJECT_VERSION"] || "1"
ext_marketing_version = app_first_settings["MARKETING_VERSION"] || "1.0"

# Xcode wants Info.plist / xcconfig paths relative to the project dir (SRCROOT =
# ios/App). native/ lives at the repo root, two levels up.
info_plist_rel = "../../native/ShareExtension/Info.plist"

ext_target.build_configurations.each do |config|
  config.build_settings.merge!(
    # new_target doesn't set PRODUCT_NAME for app extensions; without it the
    # built wrapper is named ".appex" (empty), and two build commands collide
    # on that path ("Multiple commands produce …/.appex").
    "PRODUCT_NAME" => "$(TARGET_NAME)",
    "PRODUCT_BUNDLE_IDENTIFIER" => ext_bundle_id,
    # Match the parent app's version (see note above) so archives validate.
    "CURRENT_PROJECT_VERSION" => ext_current_version,
    "MARKETING_VERSION" => ext_marketing_version,
    "INFOPLIST_FILE" => info_plist_rel,
    # We ship our own Info.plist, so don't let Xcode synthesize one.
    "GENERATE_INFOPLIST_FILE" => "NO",
    "IPHONEOS_DEPLOYMENT_TARGET" => DEPLOYMENT_TARGET,
    "SWIFT_VERSION" => "5.0",
    "TARGETED_DEVICE_FAMILY" => "1,2",
    "SKIP_INSTALL" => "YES",
    "CLANG_ENABLE_MODULES" => "YES",
    "LD_RUNPATH_SEARCH_PATHS" =>
      "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks",
    # Free/personal-team friendly default; CI overrides with
    # CODE_SIGNING_ALLOWED=NO on the xcodebuild command line.
    "CODE_SIGN_STYLE" => "Automatic",
    # Also build the extension for Mac Catalyst so it reaches the macOS share
    # menu. Xcode derives MACOSX_DEPLOYMENT_TARGET from the iOS floor, so no
    # separate Mac version is needed.
    "SUPPORTS_MACCATALYST" => "YES",
    # macOS ALWAYS sandboxes an app extension ("plugin" profile), and without
    # network.client the extension's URLSession POST to the ingest endpoint is
    # silently denied — the share never leaves the machine. Grant the sandbox +
    # outbound network via an entitlements file. Scope it to the macOS SDK (which
    # is what Mac Catalyst builds against) so iOS device signing — which has no
    # such entitlements in its provisioning profile — is untouched.
    "CODE_SIGN_ENTITLEMENTS[sdk=macosx*]" => "../../native/ShareExtension/ShareExtension.entitlements",
  )
end

# --- Source group + files -----------------------------------------------------
# Reference the hand-authored files in place (native/ stays the source of
# truth) rather than copying them into ios/.
group = project.main_group.new_group(EXT_NAME, NATIVE_DIR)
swift_ref = group.new_file(SWIFT_SOURCE)
ext_target.add_file_references([swift_ref])
# Keep the Info.plist + entitlements visible in the navigator (not build inputs;
# the entitlements is referenced via CODE_SIGN_ENTITLEMENTS above).
group.new_file(INFO_PLIST)
group.new_file(ENTITLEMENTS) if File.exist?(ENTITLEMENTS)

# --- Wire the ingest-key xcconfig --------------------------------------------
# Secrets.xcconfig provides OTB_INGEST_API_KEY, substituted into Info.plist at
# build time. It's gitignored, so it may be absent on a fresh checkout / in CI;
# the caller is responsible for creating it (docs for local, a dummy in CI).
# We wire the reference either way — a missing base config is a warning, not a
# hard failure, so the target still builds with an empty key.
secrets_ref = group.new_file(SECRETS_XCCONFIG)
ext_target.build_configurations.each do |config|
  config.base_configuration_reference = secrets_ref
end
warn "add-share-extension: note — #{SECRETS_XCCONFIG} not found; " \
     "build will use an empty OTB_INGEST_API_KEY" unless File.exist?(SECRETS_XCCONFIG)

# --- Embed the extension in the app ------------------------------------------
app_target.add_dependency(ext_target)
embed_phase = app_target.new_copy_files_build_phase("Embed App Extensions")
embed_phase.symbol_dst_subfolder_spec = :plug_ins
embed_file = embed_phase.add_file_reference(ext_target.product_reference)
embed_file.settings = { "ATTRIBUTES" => ["RemoveHeadersOnCopy"] }

# --- Enable Mac Catalyst + raise the iOS floor on the host app ---------------
# The extension only appears in the macOS share menu if BOTH it and its host
# app build for Mac Catalyst. Capacitor generates the App target as iOS-only,
# so flip it here to keep `cap add` + this script fully reproducible — otherwise
# Catalyst is a hand-click in Xcode that any regenerate of `ios/` silently wipes.
# Also raise the App target's deployment target to match the extension (Capacitor
# generates it at 13.0), so the whole app shares one iOS floor.
app_target.build_configurations.each do |config|
  config.build_settings["SUPPORTS_MACCATALYST"] = "YES"
  config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = DEPLOYMENT_TARGET
end

# Raise the project-level default too, so any target inheriting it (and the
# Xcode "iOS Deployment Target" shown for the project) matches.
project.build_configurations.each do |config|
  config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = DEPLOYMENT_TARGET
end

project.save

# --- App display name in the macOS Sharing pane ------------------------------
# macOS "Login Items & Extensions ▸ Sharing" titles each provider by its
# CFBundleName, NOT CFBundleDisplayName. Capacitor generates CFBundleName as
# $(PRODUCT_NAME) => "App", so without this the app — and thus its Share
# Extension's row — shows as a generic "App". Set the real product name (also the
# Catalyst menu-bar title). The generated Info.plist is regenerated by every
# `cap add`, so patch it here to stay reproducible.
app_info_plist = File.join(REPO_ROOT, "ios", "App", "App", "Info.plist")
if File.exist?(app_info_plist)
  plist = Xcodeproj::Plist.read_from_path(app_info_plist)
  if plist["CFBundleName"] != APP_DISPLAY_NAME
    plist["CFBundleName"] = APP_DISPLAY_NAME
    Xcodeproj::Plist.write_to_path(plist, app_info_plist)
    puts "add-share-extension: set App CFBundleName = #{APP_DISPLAY_NAME.inspect}"
  end
end

puts "add-share-extension: wired `#{EXT_NAME}` (#{ext_bundle_id}) into #{APP_TARGET_NAME}"
