#!/usr/bin/env ruby
# frozen_string_literal: true

# Adds the native WidgetKit extension target to the Capacitor-generated Xcode
# project (`ios/App/App.xcodeproj`).
#
# This is the widget sibling of `scripts/add-share-extension.rb`: the whole
# `ios/` directory is generated by `cap add ios` and gitignored, so the widget
# target can't live in git as part of the project. This script is the scripted
# equivalent of adding a "Widget Extension" target by hand in Xcode — it wires
# the hand-authored source in `native/Widget/` into a real app-extension target
# (extension point `com.apple.widgetkit-extension`) so building the `App` scheme
# also compiles `OTBWidget.swift`. That's what lets CI compile the widget without
# anyone opening Xcode.
#
# Run it AFTER `add-share-extension.rb` (that script owns the app-level Catalyst
# / deployment-target / CFBundleName patches; this one only adds the widget). It
# is idempotent: re-running removes any OTBWidget target/group/embed phase it
# previously added and rebuilds them.
#
# Usage:  ruby scripts/add-widget-extension.rb
#
# Requires the `xcodeproj` gem (`gem install xcodeproj`) — same as the share
# extension script (see docs/ios-native-app.md and .github/workflows/ios-build.yml).

require "xcodeproj"

# --- Paths -------------------------------------------------------------------
REPO_ROOT = File.expand_path("..", __dir__)
PROJECT_PATH = File.join(REPO_ROOT, "ios", "App", "App.xcodeproj")
NATIVE_DIR = File.join(REPO_ROOT, "native", "Widget")
SWIFT_SOURCE = File.join(NATIVE_DIR, "OTBWidget.swift")
INFO_PLIST = File.join(NATIVE_DIR, "Info.plist")
ENTITLEMENTS = File.join(NATIVE_DIR, "OTBWidget.entitlements")
# The widget reuses the Share Extension's ingest key (OTB_INGEST_API_KEY), so
# there's a single gitignored Secrets.xcconfig to maintain for the whole app.
SECRETS_XCCONFIG = File.join(REPO_ROOT, "native", "ShareExtension", "Secrets.xcconfig")

EXT_NAME = "OTBWidget"
APP_TARGET_NAME = "App"
EMBED_PHASE_NAME = "Embed Widget Extension"
# Keep in step with add-share-extension.rb's DEPLOYMENT_TARGET. WidgetKit needs
# iOS 14+, and the SwiftUI `.containerBackground(for: .widget)` this widget uses
# needs iOS 17+; the app's 26.0 floor clears both comfortably.
DEPLOYMENT_TARGET = "26.0"

def die(message)
  warn "add-widget-extension: #{message}"
  exit 1
end

die "no Xcode project at #{PROJECT_PATH} — run `bun run cap:add` first" unless File.exist?(PROJECT_PATH)
die "missing #{SWIFT_SOURCE}" unless File.exist?(SWIFT_SOURCE)
die "missing #{INFO_PLIST}" unless File.exist?(INFO_PLIST)

project = Xcodeproj::Project.open(PROJECT_PATH)

app_target = project.targets.find { |t| t.name == APP_TARGET_NAME }
die "no `#{APP_TARGET_NAME}` target in project — is this a Capacitor iOS project?" unless app_target

# --- Idempotency: tear down anything a previous run left behind ---------------
# Scoped strictly to this widget's own embed phase / dependency / target / group
# (a distinct EMBED_PHASE_NAME and EXT_NAME), so it never disturbs the Share
# Extension target that add-share-extension.rb added.
app_target.build_phases.grep(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
          .select { |p| p.name == EMBED_PHASE_NAME }
          .each { |p| p.remove_from_project }

app_target.dependencies
          .select { |d| d.target && d.target.name == EXT_NAME }
          .each { |d| d.remove_from_project }

project.targets.select { |t| t.name == EXT_NAME }.each do |t|
  t.product_reference&.remove_from_project
  t.remove_from_project
end

project.main_group[EXT_NAME]&.remove_from_project

# --- Create the widget extension target --------------------------------------
ext_target = project.new_target(
  :app_extension,
  EXT_NAME,
  :ios,
  DEPLOYMENT_TARGET,
)

# Bundle id must be a child of the app's (Apple requires an extension id prefixed
# by the containing app's id). Derive it from the App target so it tracks any
# change to the app id.
app_bundle_id = app_target.build_configurations.first
                          .build_settings["PRODUCT_BUNDLE_IDENTIFIER"] || "es.ricojam.onthebeach"
ext_bundle_id = "#{app_bundle_id}.#{EXT_NAME}"

# Version must match the parent app or the archive is rejected. The widget's
# Info.plist reads these via $(CURRENT_PROJECT_VERSION)/$(MARKETING_VERSION);
# new_target leaves them empty, so mirror the App target's.
app_first_settings = app_target.build_configurations.first.build_settings
ext_current_version = app_first_settings["CURRENT_PROJECT_VERSION"] || "1"
ext_marketing_version = app_first_settings["MARKETING_VERSION"] || "1.0"

# Xcode wants Info.plist / entitlements paths relative to the project dir
# (SRCROOT = ios/App). native/ lives at the repo root, two levels up.
info_plist_rel = "../../native/Widget/Info.plist"

ext_target.build_configurations.each do |config|
  config.build_settings.merge!(
    # Without PRODUCT_NAME the built wrapper is named ".appex" and two build
    # commands collide on that path (same trap as the Share Extension).
    "PRODUCT_NAME" => "$(TARGET_NAME)",
    "PRODUCT_BUNDLE_IDENTIFIER" => ext_bundle_id,
    "CURRENT_PROJECT_VERSION" => ext_current_version,
    "MARKETING_VERSION" => ext_marketing_version,
    "INFOPLIST_FILE" => info_plist_rel,
    # We ship our own Info.plist, so don't let Xcode synthesize one.
    "GENERATE_INFOPLIST_FILE" => "NO",
    "IPHONEOS_DEPLOYMENT_TARGET" => DEPLOYMENT_TARGET,
    "SWIFT_VERSION" => "5.0",
    "TARGETED_DEVICE_FAMILY" => "1,2",
    "SKIP_INSTALL" => "YES",
    "CLANG_ENABLE_MODULES" => "YES",
    "LD_RUNPATH_SEARCH_PATHS" =>
      "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks",
    # Free/personal-team friendly default; CI overrides with
    # CODE_SIGNING_ALLOWED=NO on the xcodebuild command line.
    "CODE_SIGN_STYLE" => "Automatic",
    # Also build the widget for Mac Catalyst so it can appear as a macOS widget.
    # Xcode derives MACOSX_DEPLOYMENT_TARGET from the iOS floor.
    "SUPPORTS_MACCATALYST" => "YES",
    # macOS ALWAYS sandboxes an app extension, and without network.client the
    # widget's URLSession GET to /api/ingest/stats is silently denied. Grant the
    # sandbox + outbound network via an entitlements file, scoped to the macOS
    # SDK (what Mac Catalyst builds against) so iOS device signing is untouched.
    "CODE_SIGN_ENTITLEMENTS[sdk=macosx*]" => "../../native/Widget/OTBWidget.entitlements",
  )
end

# --- Source group + files -----------------------------------------------------
# Reference the hand-authored files in place (native/ stays the source of truth)
# rather than copying them into ios/.
group = project.main_group.new_group(EXT_NAME, NATIVE_DIR)
swift_ref = group.new_file(SWIFT_SOURCE)
ext_target.add_file_references([swift_ref])
# Keep the Info.plist + entitlements visible in the navigator (not build inputs;
# the entitlements is referenced via CODE_SIGN_ENTITLEMENTS above).
group.new_file(INFO_PLIST)
group.new_file(ENTITLEMENTS) if File.exist?(ENTITLEMENTS)

# --- Wire the shared ingest-key xcconfig -------------------------------------
# Secrets.xcconfig (in native/ShareExtension/) provides OTB_INGEST_API_KEY,
# substituted into the widget's Info.plist at build time. It's gitignored, so it
# may be absent on a fresh checkout / in CI; the caller creates it (docs for
# local, a dummy in CI). A missing base config is a warning, not a hard failure —
# the target still builds with an empty key (the widget then shows a dash).
secrets_ref = group.new_file(SECRETS_XCCONFIG)
ext_target.build_configurations.each do |config|
  config.base_configuration_reference = secrets_ref
end
warn "add-widget-extension: note — #{SECRETS_XCCONFIG} not found; " \
     "build will use an empty OTB_INGEST_API_KEY" unless File.exist?(SECRETS_XCCONFIG)

# --- Embed the widget in the app ---------------------------------------------
app_target.add_dependency(ext_target)
embed_phase = app_target.new_copy_files_build_phase(EMBED_PHASE_NAME)
embed_phase.symbol_dst_subfolder_spec = :plug_ins
embed_file = embed_phase.add_file_reference(ext_target.product_reference)
embed_file.settings = { "ATTRIBUTES" => ["RemoveHeadersOnCopy"] }

project.save

puts "add-widget-extension: wired `#{EXT_NAME}` (#{ext_bundle_id}) into #{APP_TARGET_NAME}"
